version: '3'
services:
  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025
  app:
    image: decidim/decidim
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
    ports:
      - 3000:3000
    links:
      - pg
    command: bundle exec puma
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@decidim.org
      - PGADMIN_DEFAULT_PASSWORD=changeme
    ports:
      - 5050:80
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
  pgadmin-data: {}
